import { css } from '@emotion/css';
import type { GrafanaTheme2 } from '@grafana/data';

export const getStyles = (theme: GrafanaTheme2) => ({
  container: css({
    display: 'flex',
    flexDirection: 'column' as const,
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
  }),
  header: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `${theme.spacing(1)} ${theme.spacing(1.5)}`,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    flexShrink: 0,
  }),
  headerTitle: css({
    fontSize: theme.typography.bodySmall.fontSize,
    fontWeight: theme.typography.fontWeightMedium,
    color: theme.colors.text.secondary,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  }),
  toolbar: css({
    display: 'flex',
    flexDirection: 'column' as const,
    gap: theme.spacing(0.5),
    padding: `${theme.spacing(0.75)} ${theme.spacing(1)}`,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    flexShrink: 0,
  }),
  toolbarRow: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(0.5),
  }),
  toolbarLabel: css({
    fontSize: 10,
    width: 34,
    flexShrink: 0,
    color: theme.colors.text.disabled,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  }),
  pillGroup: css({
    display: 'flex',
    borderRadius: theme.shape.radius.default,
    overflow: 'hidden',
    border: `1px solid ${theme.colors.border.weak}`,
  }),
  pill: css({
    all: 'unset',
    boxSizing: 'border-box',
    padding: `1px ${theme.spacing(0.75)}`,
    fontSize: 10,
    lineHeight: '18px',
    cursor: 'pointer',
    color: theme.colors.text.secondary,
    background: 'transparent',
    borderRight: `1px solid ${theme.colors.border.weak}`,
    transition: 'background 100ms ease, color 100ms ease',
    '&:last-child': {
      borderRight: 'none',
    },
    '&:hover': {
      color: theme.colors.text.primary,
      background: theme.colors.action.hover,
    },
  }),
  pillActive: css({
    color: theme.colors.text.maxContrast,
    background: theme.colors.action.selected,
    fontWeight: theme.typography.fontWeightMedium,
  }),
  searchWrap: css({
    display: 'flex',
    alignItems: 'center',
    background: theme.colors.background.secondary,
    border: `1px solid ${theme.colors.border.weak}`,
    borderRadius: theme.shape.radius.default,
    '&:hover': {
      borderColor: theme.colors.border.medium,
    },
    '&:focus-within': {
      borderColor: theme.colors.primary.border,
    },
  }),
  searchIcon: css({
    flexShrink: 0,
    marginLeft: theme.spacing(0.5),
    color: theme.colors.text.disabled,
    pointerEvents: 'none',
  }),
  searchInput: css({
    flex: 1,
    minWidth: 0,
    appearance: 'none' as const,
    background: 'transparent',
    color: theme.colors.text.primary,
    border: 'none',
    padding: `2px ${theme.spacing(0.5)}`,
    fontSize: 11,
    lineHeight: '18px',
    outline: 'none',
    '&::placeholder': {
      color: theme.colors.text.disabled,
    },
  }),
  searchToggles: css({
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    flexShrink: 0,
    padding: `0 ${theme.spacing(0.25)}`,
  }),
  searchToggle: css({
    all: 'unset',
    boxSizing: 'border-box',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 20,
    height: 18,
    fontSize: 10,
    fontWeight: 600,
    cursor: 'pointer',
    color: theme.colors.text.disabled,
    borderRadius: 3,
    border: `1px solid transparent`,
    transition: 'color 100ms ease, background 100ms ease, border-color 100ms ease',
    '&:hover': {
      color: theme.colors.text.primary,
      background: theme.colors.action.hover,
    },
  }),
  searchToggleActive: css({
    color: theme.colors.text.maxContrast,
    background: theme.colors.action.selected,
    borderColor: theme.colors.border.medium,
  }),
  treeContainer: css({
    flex: 1,
    overflowY: 'auto' as const,
    padding: `${theme.spacing(0.5)} 0`,
  }),
  emptyState: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme.spacing(4),
    color: theme.colors.text.disabled,
    fontSize: theme.typography.bodySmall.fontSize,
  }),
});
