import { css } from '@emotion/css';
import type { GrafanaTheme2 } from '@grafana/data';
import { getTokenizeControlStyles } from '../tokenizer/tokenizeControls.styles';

export const getStyles = (theme: GrafanaTheme2) => ({
  container: css({
    display: 'flex',
    flexDirection: 'column' as const,
    flex: 1,
    minHeight: 0,
    overflowY: 'auto' as const,
  }),
  stickyBar: css({
    position: 'sticky' as const,
    top: 0,
    zIndex: 1,
    background: theme.colors.background.primary,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    flexShrink: 0,
  }),
  barMeta: css({
    fontSize: theme.typography.bodySmall.fontSize,
    color: theme.colors.text.secondary,
    whiteSpace: 'nowrap',
  }),
  agentLabel: css({
    fontSize: theme.typography.bodySmall.fontSize,
    fontWeight: theme.typography.fontWeightMedium,
    color: theme.colors.text.primary,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    textDecoration: 'underline dotted',
    textUnderlineOffset: 3,
    textDecorationColor: theme.colors.border.medium,
    transition: 'text-decoration-color 120ms ease',
    '&:hover': {
      textDecorationColor: theme.colors.text.secondary,
    },
  }),
  content: css({
    padding: theme.spacing(2),
    display: 'flex',
    flexDirection: 'column' as const,
    gap: theme.spacing(2),
  }),
  section: css({
    display: 'flex',
    flexDirection: 'column' as const,
    border: `1px solid ${theme.colors.border.weak}`,
    borderRadius: theme.shape.radius.default,
    overflow: 'hidden',
  }),
  sectionHeader: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(0.75),
    padding: `${theme.spacing(0.75)} ${theme.spacing(1.5)}`,
    background: theme.colors.background.secondary,
    cursor: 'pointer',
    userSelect: 'none' as const,
    fontSize: theme.typography.bodySmall.fontSize,
    fontWeight: theme.typography.fontWeightMedium,
    color: theme.colors.text.primary,
    '&:hover': {
      background: theme.colors.action.hover,
    },
  }),
  sectionCount: css({
    fontSize: 11,
    color: theme.colors.text.secondary,
    fontWeight: 'normal',
  }),
  sectionChevron: css({
    color: theme.colors.text.secondary,
    transition: 'transform 150ms ease',
    flexShrink: 0,
  }),
  sectionChevronExpanded: css({
    transform: 'rotate(90deg)',
  }),
  sectionContent: css({
    padding: theme.spacing(1.5),
    borderTop: `1px solid ${theme.colors.border.weak}`,
    fontSize: theme.typography.bodySmall.fontSize,
    lineHeight: 1.6,
  }),
  messageBlock: css({
    padding: `${theme.spacing(1)} 0`,
    fontSize: theme.typography.bodySmall.fontSize,
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    '&:not(:last-child)': {
      borderBottom: `1px solid ${theme.colors.border.weak}`,
    },
  }),
  messageRole: css({
    fontSize: 10,
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
    color: theme.colors.text.secondary,
    marginBottom: theme.spacing(0.5),
  }),
  messageRoleUser: css({
    color: theme.isDark ? 'oklch(0.75 0.12 260)' : 'oklch(0.50 0.15 260)',
  }),
  messageRoleAssistant: css({
    color: theme.isDark ? 'oklch(0.75 0.10 140)' : 'oklch(0.45 0.12 140)',
  }),
  messageRoleTool: css({
    color: theme.isDark ? 'oklch(0.75 0.10 180)' : 'oklch(0.45 0.12 180)',
  }),
  messageText: css({
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    color: theme.colors.text.primary,
  }),
  toolCallInline: css({
    padding: theme.spacing(1),
    borderRadius: theme.shape.radius.default,
    background: theme.colors.background.secondary,
    border: `1px dashed ${theme.colors.border.medium}`,
    fontFamily: theme.typography.fontFamilyMonospace,
    fontSize: 11,
    marginTop: theme.spacing(0.5),
    transition: 'outline-color 300ms ease, background 300ms ease',
  }),
  toolCallHighlight: css({
    outline: `2px solid ${theme.colors.primary.border}`,
    outlineOffset: 2,
    background: theme.isDark ? 'oklch(0.30 0.05 260 / 0.4)' : 'oklch(0.90 0.05 260 / 0.4)',
  }),
  toolCallInlineName: css({
    fontWeight: theme.typography.fontWeightMedium,
    color: theme.isDark ? 'oklch(0.75 0.10 180)' : 'oklch(0.45 0.12 180)',
    marginBottom: theme.spacing(0.25),
  }),
  toolCallInlineArgs: css({
    color: theme.colors.text.secondary,
    maxHeight: 200,
    overflow: 'auto',
    whiteSpace: 'pre-wrap' as const,
  }),
  usageChips: css({
    fontSize: theme.typography.bodySmall.fontSize,
    fontVariantNumeric: 'tabular-nums',
    fontFamily: theme.typography.fontFamilyMonospace,
    color: theme.colors.text.secondary,
    whiteSpace: 'nowrap',
    letterSpacing: '0.02em',
    justifySelf: 'center',
  }),
  usageSep: css({
    margin: `0 ${theme.spacing(0.75)}`,
    color: theme.colors.border.medium,
  }),
  drilldownLink: css({
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(0.5),
    fontSize: theme.typography.bodySmall.fontSize,
    color: theme.colors.text.link,
    textDecoration: 'none',
    '&:hover': {
      color: theme.colors.text.primary,
      textDecoration: 'underline',
    },
  }),
  attrGrid: css({
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: theme.spacing(1),
  }),
  attrItem: css({
    display: 'flex',
    flexDirection: 'column' as const,
    gap: theme.spacing(0.25),
  }),
  attrLabel: css({
    fontSize: 10,
    color: theme.colors.text.secondary,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  }),
  toolList: css({
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: theme.spacing(0.5),
  }),
  toolChip: css({
    display: 'inline-flex',
    padding: `${theme.spacing(0.25)} ${theme.spacing(0.75)}`,
    borderRadius: theme.shape.radius.pill,
    fontSize: 11,
    background: theme.colors.background.secondary,
    border: `1px solid ${theme.colors.border.weak}`,
    color: theme.colors.text.primary,
    fontFamily: theme.typography.fontFamilyMonospace,
  }),
  errorBanner: css({
    padding: theme.spacing(1),
    borderRadius: theme.shape.radius.default,
    background: theme.colors.error.transparent,
    border: `1px solid ${theme.colors.error.border}`,
    color: theme.colors.error.text,
    fontSize: theme.typography.bodySmall.fontSize,
  }),
  navBar: css({
    display: 'grid',
    gridTemplateColumns: '1fr auto 1fr',
    alignItems: 'center',
    padding: `${theme.spacing(1)} ${theme.spacing(1.5)}`,
    flexShrink: 0,
    gap: theme.spacing(1),
  }),
  navButton: css({
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(0.5),
    padding: `${theme.spacing(0.5)} ${theme.spacing(1)}`,
    borderRadius: theme.shape.radius.pill,
    fontSize: theme.typography.bodySmall.fontSize,
    color: theme.colors.text.secondary,
    cursor: 'pointer',
    background: theme.colors.background.secondary,
    transition: 'color 120ms ease, background 120ms ease',
    '&:hover': {
      color: theme.colors.text.primary,
      background: theme.colors.action.hover,
    },
  }),
  navButtonPrev: css({
    justifySelf: 'start',
  }),
  navButtonNext: css({
    justifySelf: 'end',
  }),
  navButtonLabel: css({
    maxWidth: 200,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontVariantNumeric: 'tabular-nums',
  }),
  kbd: css({
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 16,
    height: 16,
    padding: `0 ${theme.spacing(0.375)}`,
    borderRadius: 3,
    border: `1px solid ${theme.colors.border.weak}`,
    background: 'transparent',
    fontSize: 9,
    fontFamily: theme.typography.fontFamilyMonospace,
    color: theme.colors.text.disabled,
    lineHeight: 1,
  }),
  navCenter: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
    justifySelf: 'center',
  }),
  tipContainer: css({
    display: 'flex',
    flexDirection: 'column' as const,
    gap: theme.spacing(1.25),
    maxWidth: 420,
    maxHeight: 480,
    overflowY: 'auto' as const,
    fontSize: theme.typography.bodySmall.fontSize,
  }),
  tipTagRow: css({
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: theme.spacing(0.5),
  }),
  tipTag: css({
    display: 'inline-flex',
    padding: `${theme.spacing(0.25)} ${theme.spacing(0.75)}`,
    borderRadius: theme.shape.radius.pill,
    fontSize: 11,
    background: theme.colors.background.secondary,
    border: `1px solid ${theme.colors.border.weak}`,
    color: theme.colors.text.secondary,
    fontFamily: theme.typography.fontFamilyMonospace,
  }),
  tipSection: css({
    display: 'flex',
    flexDirection: 'column' as const,
    gap: theme.spacing(0.5),
  }),
  tipSectionLabel: css({
    fontSize: 10,
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
    color: theme.colors.text.secondary,
  }),
  scoreChipsContainer: css({
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: theme.spacing(0.5),
  }),
  scoreChip: css({
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(0.375),
    padding: `${theme.spacing(0.25)} ${theme.spacing(0.75)}`,
    borderRadius: theme.shape.radius.pill,
    fontSize: 11,
    fontFamily: theme.typography.fontFamilyMonospace,
    border: '1px solid',
    lineHeight: 1.4,
  }),
  scoreChipPass: css({
    background: theme.colors.success.transparent,
    borderColor: theme.colors.success.border,
  }),
  scoreChipFail: css({
    background: theme.colors.error.transparent,
    borderColor: theme.colors.error.border,
  }),
  scoreChipNeutral: css({
    background: theme.colors.background.secondary,
    borderColor: theme.colors.border.weak,
  }),
  scoreChipEvaluator: css({
    color: theme.colors.text.secondary,
  }),
  scoreChipSep: css({
    color: theme.colors.text.disabled,
  }),
  scoreChipKey: css({
    color: theme.colors.text.primary,
    fontWeight: theme.typography.fontWeightMedium,
  }),
  scoreChipValue: css({
    color: theme.colors.text.primary,
  }),
  scoreChipPassIcon: css({
    color: theme.colors.success.text,
    fontWeight: theme.typography.fontWeightMedium,
  }),
  scoreChipFailIcon: css({
    color: theme.colors.error.text,
    fontWeight: theme.typography.fontWeightMedium,
  }),
  tipSystemPrompt: css({
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    color: theme.colors.text.primary,
    lineHeight: 1.5,
    maxHeight: 160,
    overflowY: 'auto' as const,
    padding: theme.spacing(0.75),
    borderRadius: theme.shape.radius.default,
    background: theme.colors.background.secondary,
    border: `1px solid ${theme.colors.border.weak}`,
    fontSize: 11,
  }),
  ...getTokenizeControlStyles(theme),
});
