{{- if and .Values.minio.enabled (not .Values.minio.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sigil.minio.secretName" . }}
  labels:
    {{- include "sigil.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
type: Opaque
stringData:
  {{ .Values.minio.secretKeys.rootUser }}: {{ .Values.minio.rootUser | quote }}
  {{ .Values.minio.secretKeys.rootPassword }}: {{ .Values.minio.rootPassword | quote }}
{{- end }}
