{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sigil.minio.fullname" . }}
  labels:
    {{- include "sigil.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      targetPort: api
      protocol: TCP
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
  selector:
    {{- include "sigil.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
{{- end }}
