{{- if and .Values.minio.enabled .Values.minio.persistence.enabled (not .Values.minio.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sigil.minio.fullname" . }}-data
  labels:
    {{- include "sigil.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  accessModes:
    {{- toYaml .Values.minio.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
  {{- with .Values.minio.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
