{{- if and .Values.mysql.enabled .Values.mysql.persistence.enabled (not .Values.mysql.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sigil.mysql.fullname" . }}-data
  labels:
    {{- include "sigil.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  accessModes:
    {{- toYaml .Values.mysql.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
  {{- with .Values.mysql.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
