{{- if and .Values.mysql.enabled (not .Values.mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sigil.mysql.authSecretName" . }}
  labels:
    {{- include "sigil.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
type: Opaque
stringData:
  {{ .Values.mysql.auth.passwordKey }}: {{ .Values.mysql.auth.password | quote }}
  {{ .Values.mysql.auth.rootPasswordKey }}: {{ .Values.mysql.auth.rootPassword | quote }}
{{- end }}
