{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sigil.prometheus.fullname" . }}
  labels:
    {{- include "sigil.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yaml: |
{{ tpl .Values.prometheus.config . | nindent 4 }}
{{- end }}
