apiVersion: v1
kind: Service
metadata:
  name: {{ include "sigil.fullname" . }}
  labels:
    {{- include "sigil.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: otlp-grpc
      port: {{ .Values.service.ports.otlpGrpc }}
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: {{ .Values.service.ports.otlpHttp }}
      targetPort: otlp-http
      protocol: TCP
  selector:
    {{- include "sigil.selectorLabels" . | nindent 4 }}
