{{- if and .Values.tempo.enabled .Values.tempo.persistence.enabled (not .Values.tempo.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sigil.tempo.fullname" . }}-data
  labels:
    {{- include "sigil.labels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
spec:
  accessModes:
    {{- toYaml .Values.tempo.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.tempo.persistence.size }}
  {{- with .Values.tempo.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
