FROM golang:1.26-bookworm@sha256:c7a82e9e2df2fea5d8cb62a16aa6f796d2b2ed81ccad4ddd2bc9f0d22936c3f2

WORKDIR /app/sigil

ENV GOCACHE /opt/go-cache/build
ENV GOMODCACHE /opt/go-cache/mod

RUN go install github.com/air-verse/air@v1.62.0

CMD ["air", "-c", ".air.toml"]
