services:
  grafana:
    user: root
    container_name: 'sigil-grafana'
    build:
      context: ..
      dockerfile: .config/Dockerfile
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-oss}
        grafana_version: ${GRAFANA_VERSION:-12.3.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - '3000:3000'
      - '2345:2345'
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - sigil-plugin-dist:/var/lib/grafana/plugins/grafana-sigil-app
      - ../provisioning:/etc/grafana/provisioning
      - ../apps/plugin:/root/sigil/apps/plugin
    environment:
      NODE_ENV: development
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-sigil-app
