FROM node:24-bookworm@sha256:3a09aa6354567619221ef6c45a5051b671f953f0a1924d1f819ffb236e520e6b

ENV GOPATH /opt/go
ENV PATH $PATH:$GOPATH/bin:/usr/local/go/bin
ENV GOCACHE /opt/go-cache/build
ENV GOMODCACHE /opt/go-cache/mod
ENV GOFLAGS="-buildvcs=false"

COPY --from=golang:1.26-bookworm@sha256:c7a82e9e2df2fea5d8cb62a16aa6f796d2b2ed81ccad4ddd2bc9f0d22936c3f2 /usr/local/go/ /usr/local/go/
RUN /usr/local/go/bin/go install github.com/magefile/mage@v1.15.0

COPY package.json /tmp/package.json
RUN corepack enable && cd /tmp && corepack install
RUN pnpm config set store-dir /opt/pnpm-store

EXPOSE 35728
EXPOSE 35729
