CREATE DATABASE IF NOT EXISTS grafana;
CREATE DATABASE IF NOT EXISTS sigil;

CREATE USER IF NOT EXISTS 'sigil'@'%' IDENTIFIED BY 'sigil';
GRANT ALL PRIVILEGES ON sigil.* TO 'sigil'@'%';
GRANT ALL PRIVILEGES ON grafana.* TO 'sigil'@'%';
FLUSH PRIVILEGES;
